---
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/python:3.12
      - image: cimg/postgres:latest
        environment:
          POSTGRES_DB: django
          POSTGRES_PASSWORD: postgres
      - image: minio/minio:latest
        command: server /data
        environment:
          MINIO_ACCESS_KEY: minioAccessKey
          MINIO_SECRET_KEY: minioSecretKey
      - image: arangodb/arangodb:3.5.6
        environment:
          ARANGO_ROOT_PASSWORD: letmein
    steps:
      - checkout
      - run:
          name: Install tox
          command: sudo pip install tox
      - run:
          name: Run tests
          command: tox
          environment:
            DJANGO_DATABASE_URL: postgres://postgres:postgres@localhost:5432/django
            DJANGO_MINIO_STORAGE_ENDPOINT: localhost:9000
            DJANGO_MINIO_STORAGE_ACCESS_KEY: minioAccessKey
            DJANGO_MINIO_STORAGE_SECRET_KEY: minioSecretKey
            DJANGO_MULTINET_ARANGO_URL: http://localhost:8529
            DJANGO_MULTINET_ARANGO_PASSWORD: letmein
            DJANGO_MULTINET_ARANGO_READONLY_PASSWORD: letmein
workflows:
  version: 2
  ci:
    jobs:
      - test
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
