# Generated by Django 3.2.5 on 2021-08-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['id'], 'permissions': [('owner', 'Owns the workspace'), ('maintainer', 'Grants roles except owner on the workspace'), ('reader', 'Creates and deletes data on the workspace'), ('writer', 'Views data on the workspace')]},
        ),
        migrations.AddField(
            model_name='workspace',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
