# Generated by Django 3.2.5 on 2021-08-05 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_upload'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='workspace',
            name='public',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WorkspacePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'Reader'), (2, 'Writer'), (3, 'Maintainer'), (4, 'Owner')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.workspace')),
            ],
        ),
        migrations.AddConstraint(
            model_name='workspacepermission',
            constraint=models.UniqueConstraint(fields=('workspace', 'user'), name='unique_workspace_permission'),
        ),
        migrations.AddConstraint(
            model_name='workspacepermission',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 4)), fields=('workspace',), name='single_workspace_owner'),
        ),
    ]
