# Generated by Django 3.2.5 on 2021-07-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_workspace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['id'], 'permissions': [('owner', 'Owns the workspace'), ('maintainer', 'May grant all roles but owner on the workspace'), ('writer', 'May write to and remove from the workspace'), ('reader', 'May read and perform non-mutating queries on the workspace')]},
        ),
        migrations.AddField(
            model_name='workspace',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
