# Generated by Django 3.2.5 on 2021-08-09 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_auto_20210806_1311'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workspacerole',
            name='singe_workspace_owner',
        ),
        migrations.AddField(
            model_name='workspace',
            name='owner',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.PROTECT, to='auth.user'
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspacerole',
            name='role',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'Reader'), (2, 'Writer'), (3, 'Maintainer')]
            ),
        ),
    ]
