# Generated by Django 3.2.5 on 2021-07-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210727_1549'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['id'], 'permissions': [('owner', 'Owns the workspace'), ('maintainer', 'Grants roles except owner on the workspace'), ('reader', 'Creates and deletes data on the workspace'), ('writer', 'Views data on the workspace')]},
        ),
    ]
