# Generated by Django 3.2.5 on 2021-08-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210812_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspacerole',
            name='role',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'reader'), (2, 'writer'), (3, 'maintainer')]
            ),
        ),
    ]
