# Generated by Django 3.2.5 on 2021-09-01 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_workspacerole_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={},
        ),
    ]
