# Generated by Django 3.2.5 on 2021-07-28 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_workspace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'ordering': ['id']},
        ),
    ]
