# Generated by Django 3.2.12 on 2022-08-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210927_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='aqlquery',
            name='bind_vars',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
