# Generated by Django 3.2.18 on 2023-02-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_aqlquery_bind_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='data_type',
            field=models.CharField(choices=[('CSV', 'Csv'), ('JSON', 'Json'), ('D3_JSON', 'D3 Json'), ('NESTED_JSON', 'Nested Json'), ('NEWICK', 'Newick')], max_length=20),
        ),
    ]
