# Generated by Django 3.2.16 on 2023-04-27 16:12

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_upload_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=300)),
                ('state', models.JSONField()),
                ('network', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.network')),
                ('table', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.table')),
            ],
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('network__isnull', True), ('table__isnull', False)), models.Q(('network__isnull', False), ('table__isnull', True)), _connector='OR'), name='network_xor_table'),
        ),
    ]
