# Generated by Django 3.2.18 on 2023-08-04 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_networksession_tablesession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabletypeannotation',
            name='type',
            field=models.CharField(choices=[('primary key', 'Primary'), ('edge source', 'Source'), ('edge target', 'Target'), ('label', 'Label'), ('string', 'String'), ('boolean', 'Boolean'), ('category', 'Category'), ('number', 'Number'), ('date', 'Date'), ('ignored', 'Ignored')], max_length=16),
        ),
        migrations.AlterField(
            model_name='upload',
            name='data_type',
            field=models.CharField(choices=[('CSV', 'Csv'), ('JSON_TABLE', 'Json Table'), ('JSON_NETWORK', 'Json Network')], max_length=20),
        ),
    ]
