# Generated by Django 3.2.18 on 2023-08-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230804_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='networksession',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tablesession',
            name='starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workspace',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
